
package view.forms;

import DAO.AppointmentRequestDAO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Model_AppointmentRequest;
import java.util.List;

/**
 *
 * @author nadis
 */
public class PatientRequestForm extends javax.swing.JPanel {

    
    private AppointmentRequestDAO dao;
    private List<Model_AppointmentRequest> listRequests;
    private int loggedInReceptionistId;

    public PatientRequestForm() {
        initComponents();
        this.loggedInReceptionistId = 10;
        this.dao = new AppointmentRequestDAO();
        loadTableData();
    }

    public PatientRequestForm(int receptionistUserId) {
        initComponents();
        this.loggedInReceptionistId = receptionistUserId;
        this.dao = new AppointmentRequestDAO();
        loadTableData();
    }

    public void loadTableData() {
        DefaultTableModel model = new DefaultTableModel(
                new String[]{"Req ID", "Patient ID", "Name", "Email", "Date", "Slot", "Notes", "Status"}, 0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        jTable1.setModel(model);

        listRequests = dao.getAllRequests();

        if (listRequests != null) {
            for (Model_AppointmentRequest req : listRequests) {
                model.addRow(new Object[]{
                    req.getRequestId(),
                    req.getPatientCustomId(),
                    req.getPatientName(),
                    req.getPatientEmail(),
                    req.getPreferredDate(),
                    req.getPreferredTimeSlot(),
                    req.getNotes(),
                    req.getStatus()
                });
            }
        }
    }

    private void updateSelectedStatus(String newStatus) {
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow != -1) {
            int requestId = (int) jTable1.getValueAt(selectedRow, 0);

            int confirm = JOptionPane.showConfirmDialog(this,
                    "Are you sure you want to mark Request ID " + requestId + " as " + newStatus + "?",
                    "Confirm Action",
                    JOptionPane.YES_NO_OPTION);

            if (confirm == JOptionPane.YES_OPTION) {
                if (dao.updateStatus(requestId, newStatus)) {
                    JOptionPane.showMessageDialog(this, "Status updated to " + newStatus + " successfully!");
                    loadTableData();
                } else {
                    JOptionPane.showMessageDialog(this, "Failed to update status in database.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this,
                    "Please select a row from the table first!",
                    "No Selection",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ConfirmRbtn = new javax.swing.JButton();
        RejectRbtn = new javax.swing.JButton();
        ScheduleAbtn = new javax.swing.JButton();

        setForeground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Req ID", "Patient ID", "Name", "Email", "Date", "Slot", "Notes", "Status"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        ConfirmRbtn.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        ConfirmRbtn.setText("Confirm Request");
        ConfirmRbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmRbtnActionPerformed(evt);
            }
        });

        RejectRbtn.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        RejectRbtn.setText("Reject Request");
        RejectRbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RejectRbtnActionPerformed(evt);
            }
        });

        ScheduleAbtn.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        ScheduleAbtn.setText("Schedule Appointment");
        ScheduleAbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScheduleAbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(ConfirmRbtn)
                        .addGap(50, 50, 50)
                        .addComponent(RejectRbtn)
                        .addGap(50, 50, 50)
                        .addComponent(ScheduleAbtn))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 766, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConfirmRbtn)
                    .addComponent(RejectRbtn)
                    .addComponent(ScheduleAbtn))
                .addContainerGap(23, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ConfirmRbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmRbtnActionPerformed
        // TODO add your handling code here:
        updateSelectedStatus("CONFIRMED");
    }//GEN-LAST:event_ConfirmRbtnActionPerformed

    private void RejectRbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RejectRbtnActionPerformed
        // TODO add your handling code here:
        updateSelectedStatus("REJECTED");
    }//GEN-LAST:event_RejectRbtnActionPerformed

    private void ScheduleAbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScheduleAbtnActionPerformed
        // TODO add your handling code here:
        try {
            int selectedRow = jTable1.getSelectedRow();

            if (selectedRow != -1) {
                Object idObj = jTable1.getValueAt(selectedRow, 0);
                if (idObj == null) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Selected row has invalid ID!");
                    return;
                }
                int requestId = Integer.parseInt(idObj.toString());

                String patientCustomId = jTable1.getValueAt(selectedRow, 1) != null ? jTable1.getValueAt(selectedRow, 1).toString() : "";
                String patientName = jTable1.getValueAt(selectedRow, 2) != null ? jTable1.getValueAt(selectedRow, 2).toString() : "";

                java.sql.Date preferredDate = null;
                Object dateObj = jTable1.getValueAt(selectedRow, 3);
                if (dateObj instanceof java.sql.Date) {
                    preferredDate = (java.sql.Date) dateObj;
                } else if (dateObj != null) {
                    try {
                        preferredDate = java.sql.Date.valueOf(dateObj.toString());
                    } catch (Exception e) {
                    }
                }

                String preferredTimeSlot = jTable1.getValueAt(selectedRow, 4) != null ? jTable1.getValueAt(selectedRow, 4).toString() : "";

                Model_AppointmentRequest selectedRequest = new Model_AppointmentRequest(
                        requestId, patientCustomId, patientName, "", preferredDate, preferredTimeSlot, "", "", ""
                );
                ScheduleAppointmentDialog dialog = new ScheduleAppointmentDialog(selectedRequest, loggedInReceptionistId);
                dialog.setLocationRelativeTo(this);
                dialog.setVisible(true);

            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Please select an appointment request from the table first.");
            }
        } catch (Exception e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Error opening dialog: " + e.getMessage());
        }
    }//GEN-LAST:event_ScheduleAbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConfirmRbtn;
    private javax.swing.JButton RejectRbtn;
    private javax.swing.JButton ScheduleAbtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
