/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.forms;

import DAO.AppointmentRequestDAO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Model_AppointmentRequest;
import java.util.List;

/**
 *
 * @author nadis
 */
public class PatientRequestForm extends javax.swing.JPanel {

    /**
     * Creates new form PatientRequestForm
     */
    private AppointmentRequestDAO dao;
    public PatientRequestForm() {
        initComponents();
        dao = new AppointmentRequestDAO();
        loadTableData();
    }
    
    public void loadTableData() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        
        List<Model_AppointmentRequest> requests = dao.getAllRequests();
        
        for (Model_AppointmentRequest req : requests) {
            model.addRow(new Object[]{
                req.getRequestId(),
                req.getPatientCustomId(),
                req.getPatientName(),
                req.getPatientEmail(),
                req.getPreferredDate(),
                req.getPreferredTimeSlot(),
                req.getNotes(),
                req.getStatus()
            });
        }
    }
    
    private void updateSelectedStatus(String newStatus) {
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow != -1) {
            int requestId = (int) jTable1.getValueAt(selectedRow, 0);
            
            int confirm = JOptionPane.showConfirmDialog(this, 
                "Are you sure you want to mark Request ID " + requestId + " as " + newStatus + "?", 
                "Confirm Action", 
                JOptionPane.YES_NO_OPTION);

            if (confirm == JOptionPane.YES_OPTION) {
                if (dao.updateStatus(requestId, newStatus)) {
                    JOptionPane.showMessageDialog(this, "Status updated to " + newStatus + " successfully!");
                    loadTableData();
                } else {
                    JOptionPane.showMessageDialog(this, "Failed to update status in database.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, 
                "Please select a row from the table first!", 
                "No Selection", 
                JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ConfirmRbtn = new javax.swing.JButton();
        RejectRbtn = new javax.swing.JButton();
        ScheduleAbtn = new javax.swing.JButton();

        setForeground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Req ID", "Patient ID", "Name", "Email", "Date", "Slot", "Notes", "Status"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        ConfirmRbtn.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        ConfirmRbtn.setText("Confirm Request");
        ConfirmRbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmRbtnActionPerformed(evt);
            }
        });

        RejectRbtn.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        RejectRbtn.setText("Reject Request");
        RejectRbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RejectRbtnActionPerformed(evt);
            }
        });

        ScheduleAbtn.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        ScheduleAbtn.setText("Schedule Appointment");
        ScheduleAbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScheduleAbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(ConfirmRbtn)
                        .addGap(50, 50, 50)
                        .addComponent(RejectRbtn)
                        .addGap(50, 50, 50)
                        .addComponent(ScheduleAbtn))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 766, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConfirmRbtn)
                    .addComponent(RejectRbtn)
                    .addComponent(ScheduleAbtn))
                .addContainerGap(23, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ConfirmRbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmRbtnActionPerformed
        // TODO add your handling code here:
        updateSelectedStatus("CONFIRMED");
    }//GEN-LAST:event_ConfirmRbtnActionPerformed

    private void RejectRbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RejectRbtnActionPerformed
        // TODO add your handling code here:
        updateSelectedStatus("REJECTED");
    }//GEN-LAST:event_RejectRbtnActionPerformed

    private void ScheduleAbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScheduleAbtnActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ScheduleAbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConfirmRbtn;
    private javax.swing.JButton RejectRbtn;
    private javax.swing.JButton ScheduleAbtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
