/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.forms;

import DAO.AppointmentRequestDAO;
import java.awt.Color;
import javax.swing.table.DefaultTableModel;
import model.Model_AppointmentRequest;
import model.User;
import java.util.List;

/**
 *
 * @author nadis
 */
public class UserProfile extends javax.swing.JPanel {

    /**
     * Creates new form UserProfile
     */
    private User currentUser;

    public UserProfile() {
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
    }

    public void setUserData(User user) {
        this.currentUser = user;
        setBackground(new Color(0, 0, 0, 0));
        loadDataToUI();
    }

    private void loadDataToUI() {
        if (currentUser == null) {
            return;
        }

        usernameLable.setText(currentUser.getUsername());
        userRoleLable.setText(currentUser.getRole());
        emailLable.setText("Email: " + (currentUser.getEmail() != null ? currentUser.getEmail() : "N/A"));
        statusLabel.setText("Status: " + (currentUser.getStatus() != null ? currentUser.getStatus() : "ACTIVE"));

        String contact_no = currentUser.getContactNo();
        String whatsapp = currentUser.getWhatsappNo();
        String address = currentUser.getAddress();

        contactLabel.setText("Contact: " + (contact_no != null && !contact_no.trim().isEmpty() ? contact_no : "N/A"));
        whatsappLabel.setText("WhatsApp: " + (whatsapp != null && !whatsapp.trim().isEmpty() ? whatsapp : "N/A"));
        addressLabel.setText("Address: " + (address != null && !address.trim().isEmpty() ? address : "N/A")); 
        addressLabel.setVisible(true);

        contactLabel.setVisible(true);
        whatsappLabel.setVisible(true);

        if ("PATIENT".equalsIgnoreCase(currentUser.getRole())) {
            jScrollPane1.setVisible(true);
            loadPatientHistoryTable();
        } else {
            jScrollPane1.setVisible(false);
        }
    }

    private void loadPatientHistoryTable() {
        AppointmentRequestDAO dao = new AppointmentRequestDAO();
        List<Model_AppointmentRequest> list = dao.getRequestsByPatientUserId(currentUser.getUserId());

        String[] columnNames = {"Req ID", "Custom ID", "Date", "Slot", "Status"};
        DefaultTableModel model = new DefaultTableModel(columnNames, 0);

        for (Model_AppointmentRequest req : list) {
            model.addRow(new Object[]{
                req.getRequestId(),
                req.getPatientCustomId(),
                req.getPreferredDate(),
                req.getPreferredTimeSlot(),
                req.getStatus()
            });
        }
        jTable1.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        usernameLable = new javax.swing.JLabel();
        userRoleLable = new javax.swing.JLabel();
        emailLable = new javax.swing.JLabel();
        contactLabel = new javax.swing.JLabel();
        whatsappLabel = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        editButton = new javax.swing.JButton();
        addressLabel = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/profile.png"))); // NOI18N

        usernameLable.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        usernameLable.setText("Username");
        usernameLable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usernameLableMouseClicked(evt);
            }
        });

        userRoleLable.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        userRoleLable.setText("role");
        userRoleLable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userRoleLableMouseClicked(evt);
            }
        });

        emailLable.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        emailLable.setText("email");
        emailLable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emailLableMouseClicked(evt);
            }
        });

        contactLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        contactLabel.setText("Contact");
        contactLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contactLabelMouseClicked(evt);
            }
        });

        whatsappLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        whatsappLabel.setText("Whatsapp");
        whatsappLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                whatsappLabelMouseClicked(evt);
            }
        });

        statusLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        statusLabel.setText("Status");
        statusLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                statusLabelMouseClicked(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        editButton.setBackground(new java.awt.Color(0, 0, 255));
        editButton.setForeground(new java.awt.Color(255, 255, 255));
        editButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/edit (1).png"))); // NOI18N
        editButton.setText("edit");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        addressLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        addressLabel.setText("address");
        addressLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addressLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userRoleLable)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(usernameLable)
                                .addGap(55, 55, 55)
                                .addComponent(editButton))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(statusLabel)
                            .addComponent(whatsappLabel)
                            .addComponent(contactLabel)
                            .addComponent(emailLable)
                            .addComponent(addressLabel))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(usernameLable)
                            .addComponent(editButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userRoleLable))
                    .addComponent(jLabel1))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(emailLable)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(contactLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(whatsappLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addressLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(statusLabel))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editButtonActionPerformed

    private void usernameLableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usernameLableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameLableMouseClicked

    private void userRoleLableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userRoleLableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_userRoleLableMouseClicked

    private void emailLableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailLableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_emailLableMouseClicked

    private void contactLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactLabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_contactLabelMouseClicked

    private void whatsappLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_whatsappLabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_whatsappLabelMouseClicked

    private void statusLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statusLabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_statusLabelMouseClicked

    private void addressLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addressLabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_addressLabelMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel;
    private javax.swing.JLabel contactLabel;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel emailLable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JLabel userRoleLable;
    private javax.swing.JLabel usernameLable;
    private javax.swing.JLabel whatsappLabel;
    // End of variables declaration//GEN-END:variables
}
